export const Globals = {
    FETCH_ALL: "FETCH_ALL",
    FETCH_ALL_FULFILLED: "FETCH_ALL_FULFILLED",
    FETCH_ALL_FAILED: "FETCH_ALL_FAILED",

    FETCH: "FETCH",
    FETCH_FULFILLED: "FETCH_FULFILLED",
    FETCH_FAILED: "FETCH_FAILED"
}