export const Globals = {
    FETCH_ALL: "FETCH_ALL",
    FETCH_ALL_FULFILLED: "FETCH_ALL_FULFILLED",
    FETCH_ALL_PENDING: "FETCH_ALL_PENDING",
    FETCH_ALL_REJECTED: "FETCH_ALL_REJECTED",

    FETCH: "FETCH",
    FETCH_FULFILLED: "FETCH_FULFILLED",
    FETCH_PENDING: "FETCH_PENDING",
    FETCH_REJECTED: "FETCH_REJECTED",

    NEW_CONTACT: "NEW_CONTACT",
    GET_LOCAL: "GET_LOCAL",
    GET_LOCAL_FULFILLED: "GET_LOCAL_FULFILLED",
    GET_LOCAL_PENDING: "GET_LOCAL_PENDING",
    GET_LOCAL_REJECT: "GET_LOCAL_REJECT",

    UPDATE: "UPDATE",
    UPDATE_FULFILLED: "UPDATE_FULFILLED",
    UPDATE_PENDING: "UPDATE_PENDING",
    UPDATE_REJECTED: "UPDATE_REJECTED",

    DELETE: "DELETE",
    DELETE_FULFILLED: "DELETE_FULFILLED",
    DELETE_PENDING: "DELETE_PENDING",
    DELETE_REJECTED: "DELETE_REJECTED",

    SAVE: "SAVE",
    SAVE_FULFILLED: "SAVE_FULFILLED",
    SAVE_PENDING: "SAVE_PENDING",
    SAVE_REJECTED: "SAVE_REJECTED",
}